name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag devsecops:latest

    - name: Push the Docker image to Container Registry
      env: 
        ACR_SERVER: ${{ secrets.ACR_SERVER }}
        ACR_USER: ${{ secrets.ACR_USER }}
        ACR_PASS: ${{ secrets.ACR_PASS }}
      run: |
        docker login -u $ACR_USER -p $ACR_PASS $ACR_SERVER |      
        docker push devsecops:latest

